version: "3.3"

services:
  discovery-server:
    build: ./discovery-server/
    hostname: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ms-network
  navigation-service:
    build: ./navigation-service/
    ports:
      - "80:80"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
    networks:
     - ms-network

  places-service:
    build: ./places-service/
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka
    networks:
      - ms-network


networks:
  ms-network:
    driver: bridge